# Generated by Django 4.1.1 on 2022-09-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMedi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=256)),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Historiaclinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=256)),
                ('ciudad', models.CharField(max_length=256)),
                ('fecha_de_nacimiento', models.DateField(max_length=50)),
                ('estatura', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=256)),
                ('apellidos', models.CharField(max_length=256)),
                ('telefono', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personalmedico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Signosvitales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=20)),
                ('frec_respiratoria', models.CharField(max_length=20)),
                ('frec_cardiaca', models.CharField(max_length=20)),
                ('temperatura', models.CharField(max_length=20)),
                ('presion_arterial', models.CharField(max_length=20)),
                ('glucemias', models.CharField(max_length=20)),
            ],
        ),
    ]
