from .account import Account
from .user import User
from .persona import Persona
from .paciente import Paciente
from .familiar import Familiar
from .personalMedico import Personalmedico
from .signosVitales import Signosvitales
from .diagnostico import Diagnostico
from .historiaClinica import Historiaclinica